CREATE TABLE tb_cachorro (
    id_cachorro NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome_cachorro VARCHAR2(50),
    raca_cachorro VARCHAR2(50),
    sexo_cachorro VARCHAR2(1),
    data_cadastro DATE,
    data_atualizacao DATE,
    cachorro_ativo NUMBER(1,0),
    PRIMARY KEY (id_cachorro)
);




